### ISSUE TITLE
Create AngularJS wrapper

### ISSUE THREAD

**Issue by fmoliveira** [rpg-maker-repo/rmmv-client-js#1]
The wrapper shouldn't depend on jQuery, but on AngularJS $http service.

Keep in mind the library will become an UMD module soon, so, make the request option pluggable.

**Comment by fmoliveira** [comment]
Assigned to @fmoliveira.

**Comment by deusprogrammer** [comment]
The only reason I did this was to allow this client to be used by consumers not using angular.  What are your thoughts?

**Comment by fmoliveira** [comment]
We can easily adapt it to make it modular enough to support multiple uses:
browser with jQuery, browser with Angular and Node.js without both, using
Restify client.

The library would be able to auto detect its behaviour. :)

**Comment by deusprogrammer** [comment]
Sounds great!  I will leave it to you (since this seems to be your area of expertise).

**Comment by fmoliveira** [comment]
:+1:

**Comment by fmoliveira** [comment]
Working on #2 .
